name: "CI"
on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [6, 8, 10]
        os: [ubuntu-14.04, ubuntu-18.04]
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/npm@master
      with: "install"
