name: "CI"
on: [push]

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    strategy:
      matrix:
        node: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/npm@master
        args: "install"
